import { readFileSync, existsSync } from 'node:fs'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// A phone reaching us by LAN IP needs a secure context, so we serve HTTPS with
// a self-signed cert. Chrome on Android rejects a cert outright (no clickable
// bypass) unless it carries a subjectAltName matching the IP — plugin-basic-ssl
// issues CN=example.org with no SAN, which is why scans failed. certs/ is
// generated by openssl with the right SAN; see README.
// NO_SSL=1 serves plain HTTP for the adb-reverse route, where the phone hits
// localhost and is already a secure context.
const proxy = { '/api': 'http://localhost:8788', '/models': 'http://localhost:8788' }
const https =
  !process.env.NO_SSL && existsSync('certs/cert.pem')
    ? { key: readFileSync('certs/key.pem'), cert: readFileSync('certs/cert.pem') }
    : undefined

export default defineConfig({
  plugins: [react()],
  server: { host: true, proxy, https },
  preview: { host: true, proxy, https },
})
